### ISSUE TITLE
Graph breaks after changing title twice

### ISSUE THREAD

**Issue by CalebOh01** [Benjamin-Lee/DNAvisualization.org#131]

**Comment by Benjamin-Lee** [comment]
I can reproduce. This is weird.

**Comment by CalebOh01** [comment]
Yeah, why does it only break after the second one and not the first? And why does changing it 3 times fix it?

**Comment by Benjamin-Lee** [comment]
It also happens when you zoom in twice. Take a look at the deploys:

c6be0fd:
https://5fd74f92785a7c0008801c07--dnavisualization.netlify.app

d7ac41f4:
https://5fd7c57dcdc9190008e61bcb--dnavisualization.netlify.app

**Comment by Benjamin-Lee** [comment]
Something in d7ac41f broke it, just to be clear. Looking over the changes again, it all seems to be completely normal code.

**Comment by Benjamin-Lee** [comment]
Closed in c54a485
