### ISSUE TITLE
Add text wrapping to plotly legend

### ISSUE THREAD

**Issue by CalebOh01** [Benjamin-Lee/DNAvisualization.org#171]
![dnavisualization-2020-12-18T16_06_00 321Z](https://user-images.githubusercontent.com/61338866/102635207-047d9f80-4121-11eb-8f90-e10091b9a325.png)

**Comment by CalebOh01** [comment]
this is because the teslagen parser grabs the whole first line

**Comment by Benjamin-Lee** [comment]
We should truncate and switch to a horizontal legend on the bottom in these cases.

**Comment by CalebOh01** [comment]
- [x] Move text to the bottom
- [ ] Truncate key  name
- [ ] Add padding to the legend

**Comment by CalebOh01** [comment]
I have no idea how to fix this. The problem is the legend is now above the axis title. @Benjamin-Lee @SoumilSingh ?
![dnavisualization-2020-12-20T00_47_22 674Z](https://user-images.githubusercontent.com/61338866/102702644-059ef180-4233-11eb-8060-38193d35871e.png)

**Comment by CalebOh01** [comment]
I moved the legend back so it isn't broken for now
