### ISSUE TITLE
Allow the deletion of sequences and files that have been submitted

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/DNAvisualization.org#83]

**Comment by Benjamin-Lee** [comment]
This will need a button that triggers a modal

**Comment by Benjamin-Lee** [comment]
First, we'll want to do #100

**Comment by Benjamin-Lee** [comment]
Either use a multilevel checkbox (https://bootstrap-vue.org/docs/components/form-checkbox#indeterminate-tri-state-support) or use tabs (https://bootstrap-vue.org/docs/components/tabs) to switch between a list of files and list of sequences.

**Comment by CalebOh01** [comment]
Ok I will finish this today

**Comment by CalebOh01** [comment]
Just thinking about it. Should the file property be in the description object, in a separate array, or both?

**Comment by Benjamin-Lee** [comment]
Doesn’t matter but it’s already set up as a property so unless there’s a reason to change it, I’d stick with it. Is there something that would be easier if it were structured differently?
