### ISSUE TITLE
Make example button load HDV

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/DNAvisualization.org#87]

**Comment by Benjamin-Lee** [comment]
Actually, use a split button and enable some other options. Maybe default to SARS-CoV-2 since I bet that's what people will want to see

**Comment by CalebOh01** [comment]
Where should the sequences be stored?

**Comment by Benjamin-Lee** [comment]
For now, store it as a string in the method triggered on click

**Comment by CalebOh01** [comment]
so like an array of strings?

**Comment by Benjamin-Lee** [comment]
You can put them all in one string and the FASTA parser will split them out
